repositories:
  - apache/spark
  - MariaDB/server
  - mruby/mruby
  - rails/rails
  - ruby/ruby
  - greenplum-db/gpdb
  - greenplum-db/greenplum-db.github.io
  - mozilla-japan/gecko-embedded
webhook-end-point: http://web-hooks-receiver.commit-email.info/
