repositories:
  - apache/arrow
  - apache/spark
  - MariaDB/server
  - mruby/mruby
  - rails/rails
  - ruby/ruby
  - mozilla-japan/gecko-embedded
  - speee/webapp-revieee
webhook-end-point: http://web-hooks-receiver.commit-email.info/
